name: opensg_env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - mpi4py
  - meshio
  - petsc4py
  - pyyaml
  - fenics-dolfinx=0.8.0
  - fenics-basix=0.8.0
  - fenics-ufl=2024.1.0
  - fenics-ffcx=0.8.0
  - mpich 
  - pip
  - pip:
    - gmsh
    - -e .
