name: opensg_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - mpi4py
  - meshio
  - petsc4py=3.21.5
  - yaml
  - contextlib2  # For compatibility
  - pathlib
  - typing-extensions
  - fenics-dolfinx=0.8.0
  - fenics-basix=0.8.0
  - fenics-ufl=0.8.0
  - fenics-ffcx=0.8.0
  - mpich 
  - pyvista
  - pyyaml
  - pip
  - pip:
    - -e .
    - gmsh
