name: opensg_env
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy>=1.20.0
  - scipy>=1.7.0
  - mpi4py>=3.0.0
  - meshio
  - petsc4py>=3.18.0
  - pyyaml>=5.4.0
  - fenics-dolfinx>=0.9.0
  - fenics-basix>=0.9.0
  - fenics-ufl
  - fenics-ffcx>=0.9.0
  - mpich 
  - sphinx
  - sphinxcontrib-bibtex
  - pip
  - pip:
    - gmsh
    - -e .
